### ISSUE TITLE
':rfid_urovo_usdk' could not be found in project ':capacitor-rfid-plugin-ox'

### ISSUE THREAD

**Issue by azhar-neolysi** [Akramjon2658/capacitor-rfid-plugin-ox#3]
A problem occurred evaluating project ':capacitor-rfid-plugin-ox'.

Project with path ':rfid_urovo_usdk' could not be found in project ':capacitor-rfid-plugin-ox'.

    implementation fileTree(dir: 'libs', include: ['*.aar', '*.jar'])
    implementation project(':capacitor-android')
    implementation files('libs/platform_sdk_v3.1.221124.jar')
    api project(':rfid_urovo_usdk')
    
    libs directory missing in new update

**Comment by Akramjon2658** [comment]
You need to get SDK from distributors or owners
