### ISSUE TITLE
A problem occurred evaluating project ':capacitor-rfid-plugin-ox'

### ISSUE THREAD

**Issue by azhar-neolysi** [Akramjon2658/capacitor-rfid-plugin-ox#4]
Build file 'D:\ionic\testrfid\testrfid\node_modules\capacitor-rfid-plugin-ox\android\build.gradle' line: 59

A problem occurred evaluating project ':capacitor-rfid-plugin-ox'.
> Project with path ':rfid_urovo_usdk' could not be found in project ':capacitor-rfid-plugin-ox'.

**Comment by Akramjon2658** [comment]
You need to get SDK from distributors or owners

**Comment by arun-neolysi** [comment]
i have sdk where it add in the code
